# Generated by Django 5.1.4 on 2024-12-05 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_language_user_role_alter_user_id_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='UserID',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='user',
            new_name='UserID',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 5, 22, 52, 47, 722584, tzinfo=datetime.timezone.utc)),
        ),
    ]
