# Generated by Django 5.1.3 on 2024-11-24 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_language_alter_user_managers_user_role_alter_user_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Lesson',
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_allocated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('frequency', models.CharField(choices=[('once a week', 'Once a week'), ('once per fortnight', 'Once per fortnight')], max_length=20)),
                ('term', models.CharField(choices=[('sept-christmas', 'September-Christmas'), ('jan-easter', 'January-Easter'), ('may-july', 'May-July')], max_length=20)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrequest', to='tutorials.language')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrequest', to='tutorials.student')),
            ],
        ),
    ]
