# Generated by Django 5.1.3 on 2024-11-26 17:19

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_rename_class_lesson_studentrequest'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('tutor', 'Tutor'), ('student', 'Student'), ('admin', 'Admin')], max_length=10),
        ),
    ]
