# Generated by Django 5.1.4 on 2024-12-05 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_rename_user_student_userid_rename_user_tutor_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 5, 22, 53, 11, 868959, tzinfo=datetime.timezone.utc)),
        ),
    ]
