# Generated by Django 5.1.4 on 2024-12-06 03:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_alter_lesson_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 6, 3, 54, 22, 37772, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='TutorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default='09:00')),
                ('end_time', models.TimeField()),
                ('day', models.DateField()),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], default='available', max_length=20)),
                ('action', models.CharField(choices=[('edit', 'Edit'), ('delete', 'Delete')], default='edit', max_length=10)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='tutorials.tutor')),
            ],
        ),
    ]
