# Generated by Django 5.1.3 on 2024-12-02 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_alter_user_managers'),
        ('tutorials', '0004_alter_user_managers_invoice_lessons_lesson_price_and_more'),
    ]

    operations = [
    ]
