# Generated by Django 5.1.3 on 2024-11-28 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_alter_user_managers_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorLangRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', 'Add Language'), ('remove', 'Remove Language'), ('change', 'Change Language')], max_length=10)),
                ('current_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_language_requests', to='tutorials.language')),
                ('language', models.ForeignKey(blank=True, help_text='Existing language in the system.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutorials.language')),
                ('requested_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_language_requests', to='tutorials.language')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_request', to='tutorials.tutor')),
            ],
        ),
    ]
