# Generated by Django 5.1.4 on 2024-12-06 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_alter_lesson_date_tutoravailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 6, 6, 21, 55, 252310, tzinfo=datetime.timezone.utc)),
        ),
    ]
