# Generated by Django 5.1.3 on 2024-11-29 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_alter_studentrequest_venue_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='previous_message',
            new_name='reply',
        ),
    ]
