# Generated by Django 5.1.4 on 2024-12-06 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_alter_lesson_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 6, 8, 9, 2, 973750, tzinfo=datetime.timezone.utc)),
        ),
    ]
