# Generated by Django 5.1.3 on 2024-11-29 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_rename_previous_message_message_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='previous_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='tutorials.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_by', to='tutorials.message'),
        ),
    ]
