# Generated by Django 5.1.2 on 2024-12-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_tutoravailability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutoravailability',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='tutoravailability',
            name='start_time',
            field=models.TimeField(default='09:00'),
        ),
    ]
