# Generated by Django 5.1.4 on 2024-12-06 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_invoice_approved_alter_lesson_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 6, 23, 41, 20, 393145, tzinfo=datetime.timezone.utc)),
        ),
    ]
