# Generated by Django 5.1.2 on 2024-12-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_rename_time_tutoravailability_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoravailability',
            name='action',
            field=models.CharField(choices=[('edit', 'Edit'), ('delete', 'Delete')], default='edit', max_length=10),
        ),
    ]
