<<<<<<< HEAD
# Generated by Django 5.1.3 on 2024-12-09 13:18
=======
# Generated by Django 5.1.4 on 2024-12-06 23:41
>>>>>>> 501c93f2b415a88c4adbbc977f639ba3a85591a7

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_invoice_approved_alter_lesson_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
<<<<<<< HEAD
            field=models.DateField(default=datetime.datetime(2024, 12, 9, 13, 18, 42, 322033, tzinfo=datetime.timezone.utc)),
=======
            field=models.DateField(default=datetime.datetime(2024, 12, 6, 23, 41, 20, 393145, tzinfo=datetime.timezone.utc)),
>>>>>>> 501c93f2b415a88c4adbbc977f639ba3a85591a7
        ),
    ]
