# Generated by Django 5.1.3 on 2024-11-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0008_alter_message_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='UserID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='UserID',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='paidInvoice',
        ),
    ]
