# Generated by Django 5.1.3 on 2024-12-09 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0008_alter_lesson_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 9, 13, 42, 27, 103112, tzinfo=datetime.timezone.utc)),
        ),
    ]
