# Generated by Django 5.1.3 on 2024-12-01 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0009_rename_userid_student_user_rename_userid_tutor_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='lesson',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='invoices',
                to='tutorials.lesson',
                default=1,),
            preserve_default=False,
        ),
    ]
