# Generated by Django 5.1.4 on 2024-12-07 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0009_alter_lesson_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='lessons',
        ),
        migrations.AddField(
            model_name='lesson',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='tutorials.invoice'),
        ),
    ]
