# Generated by Django 5.1.3 on 2024-12-01 22:47

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0010_invoice_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='frequency',
            field=models.CharField(choices=[('once a week', 'Once a week'), ('once per fortnight', 'Once per fortnight')], default='once a week', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='term',
            field=models.CharField(choices=[('sept-christmas', 'September-Christmas'), ('jan-easter', 'January-Easter'), ('may-july', 'May-July')], default='sept-christmas', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='venue',
            field=models.CharField(default='TBD', max_length=255),
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
