# Generated by Django 5.1.3 on 2024-12-11 05:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0010_remove_invoice_lessons_lesson_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
