# Generated by Django 5.1.3 on 2024-12-11 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0010_alter_lesson_date'),
        ('tutorials', '0010_remove_invoice_lessons_lesson_invoice'),
    ]

    operations = [
    ]
