# Generated by Django 5.1.3 on 2024-12-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_merge_20241202_1610'),
        ('tutorials', '0012_lesson_created_at'),
    ]

    operations = [
    ]
