# Generated by Django 5.1.3 on 2024-12-03 16:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0013_merge_0005_merge_20241202_1610_0012_lesson_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='lessons',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 3, 16, 9, 56, 429234, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='invoice',
            name='lessons',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tutorials.lesson'),
        ),
    ]
