# Generated by Django 5.1.3 on 2024-12-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0008_tutoravailability_action'),
        ('tutorials', '0014_remove_invoice_lesson_remove_invoice_lessons_and_more'),
    ]

    operations = [
    ]
